export default {
  login: "godunmichal",
  id: 56390330,
  node_id: "MDQ6VXNlcjU2MzkwMzMw",
  avatar_url: "https://avatars0.githubusercontent.com/u/56390330?v=4",
  gravatar_id: "",
  url: "https://api.github.com/users/godunmichal",
  html_url: "https://github.com/godunmichal",
  followers_url: "https://api.github.com/users/godunmichal/followers",
  following_url:
    "https://api.github.com/users/godunmichal/following{/other_user}",
  gists_url: "https://api.github.com/users/godunmichal/gists{/gist_id}",
  starred_url:
    "https://api.github.com/users/godunmichal/starred{/owner}{/repo}",
  subscriptions_url: "https://api.github.com/users/godunmichal/subscriptions",
  organizations_url: "https://api.github.com/users/godunmichal/orgs",
  repos_url: "https://api.github.com/users/godunmichal/repos",
  events_url: "https://api.github.com/users/godunmichal/events{/privacy}",
  received_events_url:
    "https://api.github.com/users/godunmichal/received_events",
  type: "User",
  site_admin: false,
  name: "Michał Godun",
  company: null,
  blog: "https://michal-godun-portfolio.web.app/",
  location: "Białystok, Poland",
  email: null,
  hireable: null,
  bio: "React Frontend Developer",
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: "2019-10-10T09:53:15Z",
  updated_at: "2020-11-19T13:03:18Z",
};
